#!/usr/bin/env python3

from os.path import expanduser
import os
import sys
import requests
import json
import random
import textwrap
import argparse

home = expanduser("~")
data_directory = home + '/.qotd/'
file_name = 'quotes.json'
width_quote = 70
italic_support = True
quotes_file = data_directory + file_name

parser = argparse.ArgumentParser(prog='qotd', description='Show quote of the day.')
parser.add_argument('-u', '--update', action='store_true', help='update quote file')
args = parser.parse_args()

def download (f, exists):
    if not exists:
        print('Downloading quotes file...')
    else:
        print('Updating quotes file...')
    # Repo with quotes file
    url = 'https://github.com/dwyl/quotes/raw/master/quotes.json'
    r = requests.get(url, allow_redirects=True)
    open(f, 'wb').write(r.content)
    if not exists:
        print('{} downloaded.'.format(f))
    else:
        print('{} updated.'.format(f))
    sys.exit(0)

def show_quote (quote, author):
    if italic_support:
        author = '\x1B[3m' + data[i]['author'] + '\x1B[23m'
    else:
        author = data[i]['author']
    print('"{}" - {}'.format('\n'.join(textwrap.wrap(quote, width_quote)), author))

if not os.path.isdir(data_directory):
    os.makedirs(data_directory)

exists = os.path.isfile(quotes_file)
if not (exists) or args.update:
    download(quotes_file, exists)

with open(quotes_file) as f:
    try:
        data = json.load(f)
    except:
        print('Error quotes file not found.')
    else:
        i = random.randint(0,len(data)-1)
        q = data[i]['text']
        a = data[i]['author']
        show_quote(q,a)
